name: "Personal RSS System"
on:
    workflow_dispatch:
    schedule:
        - cron: '0 8 * * *'
jobs:
    rss:
        name: "rss step"
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8 #install python
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install requirements.txt
            - name: Scrape Sources
              run: |
                  python rss.py
              env:
                  EMAIL: ${{ secrets.EMAIL }}
                  PASSWORD: ${{ secrets.PASSWORD }}
