name: "Personal RSS System"
on:
    workflow_dispatch:
    schedule:
        - cron: '0 8 * * *'
jobs:
    rss:
        name: "rss step"
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8 #install python
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Scrape Sources
              run: |
                  echo $TARGET
                  python rss.py
              env:
                  EMAIL_USERNAME: ${{ secrets.EMAIL }}
                  EMAIL_PASSWORD: ${{ secrets.PASSWORD }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
                  REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
                  TARGET: ${{ secrets.TARGET }}

